### ISSUE TITLE
XHTML1 / HTML4 and Google Maps API v3

### ISSUE THREAD

**Issue by wouterbeek** [Anniepoo/weblog#10]
Hi Annie,

I read the following lines in weblog:
~~~{.pl}
% @tbd for unclear reasons, uncommenting this breaks the Google Maps demo.
%html_set_options([dialect(xhtml)]),
~~~

Searching the Web I found out that
  1. Google Maps API v2 strongly recommends the use of HTML5, not HTML4 or XHTML1. We are using Google Maps API v3, and documentation for that version does not even mention HTML4 or XHTML1...
  2. Nevertheless, some people have tried to render v3 Maps with XHTML1. I could not get their solutions to work though. Maybe the Google Maps API v3 has progressed since these forum posts were submitted in 2009... See https://groups.google.com/forum/#!topic/google-maps-js-api-v3/rs6Y0Cq01Ic
  3. The only thing I could 'fix' was that the generated maps page was not XHTML1 (or HTML4) compliant. In `map_demo.pl` a style element was included in the body, but this is only possible in HTML5, see the HTML4 standard for reference http://www.w3.org/TR/1999/REC-html401-19991224/present/styles.html#edef-STYLE

So... I think the conclusion might be that Maps API v3 should be used on HTML5 served Web pages exclusively (since Google does not seem to guarantee support for older HTML-parlance). Do you agree?

Cheers!,
Wouter.

**Comment by Anniepoo** [comment]
I think this is now a dead issue. Agreed, close it.
