### ISSUE TITLE
jQuery-UI dropdown menu no longer opens

### ISSUE THREAD

**Issue by wouterbeek** [Anniepoo/weblog#17]
This occurs in the "Demo jQueryUI menus" item.

**Comment by ahungry** [comment]
What page is the broken widget on?  The Navigation > Demo Menus item worked for me (Firefox 42.0 in GNU/Linux i686).

**Comment by Anniepoo** [comment]
hey ahungry.  Weblog hasn't gotten much love of late, but it works on my machine. I suspect this got fixed long ago and never got closed.
